/* clang-format off */
#include "cmp.h"

#include <stdlib.h>
#include <string.h>

#include "cmp_log.h"
/* clang-format on */

struct cmp_sandbox_exec {
  int is_initialized;
};

/**
 * @brief Create a sandbox execution environment.
 *
 * @param out_sandbox Pointer to receive the sandbox instance.
 * @return 0 on success, or an error code on failure.
 */
int cmp_sandbox_exec_create(cmp_sandbox_exec_t **out_sandbox) {
  int rc = CMP_SUCCESS;
  cmp_sandbox_exec_t *sandbox;

  rc = CMP_SUCCESS;

  if (out_sandbox == NULL) {
    LOG_DEBUG("Invalid argument: out_sandbox is NULL\n");
    return CMP_ERROR_INVALID_ARG;
  }

  rc = CMP_MALLOC(sizeof(cmp_sandbox_exec_t), (void **)&sandbox);
  if (rc != CMP_SUCCESS) {
    LOG_DEBUG("OOM\n");
    return CMP_ERROR_OOM;
  }

  sandbox->is_initialized = 1;
  *out_sandbox = sandbox;
  return rc;
}

/**
 * @brief Destroy a sandbox execution environment.
 *
 * @param sandbox The sandbox instance.
 * @return 0 on success, or an error code on failure.
 */
int cmp_sandbox_exec_destroy(cmp_sandbox_exec_t *sandbox) {
  int rc = CMP_SUCCESS;

  rc = CMP_SUCCESS;

  if (sandbox == NULL) {
    LOG_DEBUG("Invalid argument: sandbox is NULL\n");
    return CMP_ERROR_INVALID_ARG;
  }

  rc = CMP_FREE(sandbox);
  if (rc != CMP_SUCCESS) {
    LOG_DEBUG("Free failed\n");
    return rc;
  }

  return rc;
}

/**
 * @brief Execute code in a sandbox environment.
 *
 * @param sandbox The sandbox instance.
 * @param language The language of the code to execute.
 * @param code The code to execute.
 * @param out_output Pointer to receive the output of the execution.
 * @return 0 on success, or an error code on failure.
 */
int cmp_sandbox_exec_run(cmp_sandbox_exec_t *sandbox, const char *language,
                         const char *code, char **out_output) {
  int rc = CMP_SUCCESS;
  const char *dummy_output = "Hello world (mocked output)\n";
  char *res;
  size_t len;

  rc = CMP_SUCCESS;

  if (sandbox == NULL || language == NULL || code == NULL ||
      out_output == NULL) {
    LOG_DEBUG(
        "Invalid argument: sandbox, language, code or out_output is NULL\n");
    return CMP_ERROR_INVALID_ARG;
  }

  /* This is a mock. Real integration uses platform specific process launching
     (fork/exec on POSIX, CreateProcess on Win32, capturing pipes). */
  len = strlen(dummy_output);
  rc = CMP_MALLOC(len + 1, (void **)&res);
  if (rc != CMP_SUCCESS) {
    LOG_DEBUG("OOM\n");
    return CMP_ERROR_OOM;
  }

  /* Safe string copy fallback logic */
#if defined(_MSC_VER)
  if (strcpy_s(res, len + 1, dummy_output) != 0) {
    LOG_DEBUG("strcpy_s failed\n");
    CMP_FREE(res);
    return CMP_ERROR_GENERAL;
  }
#else
  strncpy(res, dummy_output, len);
  res[len] = '\0';
#endif

  *out_output = res;
  return rc;
}

/**
 * @brief Free the output generated by sandbox execution.
 *
 * @param output The output string to free.
 * @return 0 on success, or an error code on failure.
 */
int cmp_sandbox_exec_free_output(char *output) {
  int rc = CMP_SUCCESS;

  rc = CMP_SUCCESS;

  if (output != NULL) {
    rc = CMP_FREE(output);
    if (rc != CMP_SUCCESS) {
      LOG_DEBUG("Free failed\n");
      return rc;
    }
  }

  return rc;
}
