function(target_link_platform_libraries target_name visibility)
    if(WIN32 OR CYGWIN)
        target_link_libraries(${target_name} ${visibility} ws2_32 user32 gdi32 opengl32 gdiplus)
    elseif(APPLE)
        target_link_libraries(${target_name} ${visibility} "-framework Cocoa" "-framework OpenGL")
    elseif(EMSCRIPTEN)
        target_link_options(${target_name} ${visibility} "-sMIN_WEBGL_VERSION=2" "-sMAX_WEBGL_VERSION=2")
    elseif(UNIX AND NOT APPLE AND NOT CYGWIN AND NOT EMSCRIPTEN)
        if(UI_ENABLE_WAYLAND)
            target_link_libraries(${target_name} ${visibility} ${WAYLAND_LIBRARIES} GL)
        else()
            target_link_libraries(${target_name} ${visibility} GL X11)
        endif()
    endif()
endfunction()
